# docker-compose.yaml
services:
  contract-validator:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - HTTP_PROXY=""
      - HTTPS_PROXY=""
      - NO_PROXY="*"
      - GROQ_API_KEY=${GROQ_API_KEY}
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
