# docker-compose.yml
services:
  contract-validator:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
